# file: src/settings.py
# date: October 29, 2021
# description: Django settings for jotes project.
#
# note: Generated by 'django-admin startproject' using Django 3.2.8.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/3.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/3.2/ref/settings/
#
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
#
# For more information on the database, see
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
#
# For more information on password validation, see
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
#
# For more information on internationalization, see
# https://docs.djangoproject.com/en/3.2/topics/i18n/
#
# For more information on static files (CSS, JavaScript, Images), see
# https://docs.djangoproject.com/en/3.2/howto/static-files/
#
# For more information on the default primary key field type, see
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2uj%84=3zixllu4pupg*aqn49&&g=uq(72qry&v)k4a-=i2g-l'

DEBUG = True

# Application definition
ALLOWED_HOSTS = []
INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'
TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'src.wsgi.application'

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
  }
}

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
